package br.com.correios.siscap.constantes;


public interface ImpressaoID {

	String JASPER = ".jasper";
	String APPLICATION_PDF     = "application/pdf";
	String APPLICATION_MSEXCEL = "application/msexcel";
	String CONTENT_DISPOSITION = "Content-disposition";
	
	String CAMINHO_ARQUIVOS_IMPRESSAO = "/relatorios/";
	
	//CONSTANTES PARA IMPRESSAO DO COMPROVANTE DE RECEBIMENTO
	String COMPROVANTE_RECEBIMENTO = "Comprovante de Recebimento";
	String NOME_ARQUIVO_COMPROVANTE_RECEBIMENTO = "comprovante_recebimento";
	String CAMINHO_JASPER_COMPROVANTE_RECEBIMENTO = CAMINHO_ARQUIVOS_IMPRESSAO + NOME_ARQUIVO_COMPROVANTE_RECEBIMENTO + JASPER;
	
	//CONSTANTES PARA IMPRESSAO DA LISTA DE CONFERENCIA	
	String LISTA_CONFERENCIA = "Lista de Conferência";
	String NOME_ARQUIVO_LISTA_CONFERENCIA = "lista_conferencia";
	String CAMINHO_JASPER_LISTA_CONFERENCIA = CAMINHO_ARQUIVOS_IMPRESSAO + NOME_ARQUIVO_COMPROVANTE_RECEBIMENTO + JASPER;
	
	//CONSTANTES PARA IMPRESSAO DA LISTA DE COLETA
	String LISTA_COLETA = "Lista de Coleta";
	String NOME_ARQUIVO_LISTA_COLETA = "lista_coleta";
	String CAMINHO_JASPER_LISTA_COLETA = CAMINHO_ARQUIVOS_IMPRESSAO + NOME_ARQUIVO_LISTA_COLETA + JASPER;
	
	//CONSTANTES PARA IMPRESSAO DAS ETIQUETAS
	String CODIGO_BARRAS = "Código de Barras";
	String NOME_ARQUIVO_CODIGO_BARRAS = "codigo_barras";
	String CAMINHO_JASPER_CODIGO_BARRAS = CAMINHO_ARQUIVOS_IMPRESSAO + NOME_ARQUIVO_CODIGO_BARRAS + JASPER;
	
	//CONSTANTES PARA IMPRESSAO DA LISTA DE ENCAMINHAMENTO E ENTREGA
	String LISTA_ENCAMINHAMENTO_ENTREGA = "Lista de Encaminhamento / Entrega";
	String NOME_ARQUIVO_LISTA_ENCAMINHAMENTO_ENTREGA = "lista_encaminhamento_entrega";
	String CAMINHO_JASPER_LISTA_ENCAMINHAMENTO_ENTREGA = CAMINHO_ARQUIVOS_IMPRESSAO + NOME_ARQUIVO_LISTA_ENCAMINHAMENTO_ENTREGA + JASPER;
	
}